### PR TITLE
Update Chinese Translation

### PR DESCRIPTION
**Pull request by CJYKK**
Just better ;)

### CODE REVIEW

**Comment by RamonUnch** [comment]
nice, thanks

**Comment by CJYKK** [comment]
^_^

**Comment by RamonUnch** [comment]
@CJYKK 
Actually, It seems you removed the accelerator keys, Maybe it would be better to keep them at least for all the actions that are in the "Action Menu"?
Myself, when using the Action Menu, I always use the accelerator and so does @yatli So I think it would be beter to keep them...

**Comment by yatli** [comment]
Other than the accelerators, here are the actual changes:

```
<<<
BlacklistBox=忽略列表设置
BlacklistProcessBlacklist=忽略以下进程(&p)：
BlacklistBlacklist=忽略以下窗口(&w)：
BlacklistScrolllist=以下窗口忽略滚动操作(&s)：
BlacklistMDIs=将以下&MDI窗口视为单窗口：
BlacklistPause=禁止暂停以下进程(&u)：
BlacklistFindWindowBox=指定窗口
=====
BlacklistBox=黑名单设置
BlacklistProcessBlacklist=进程黑名单：
BlacklistBlacklist=窗口黑名单：
BlacklistScrolllist=应该忽略滚动操作的窗口：
BlacklistMDIs=将以下&MDI窗口视为单窗口：
BlacklistPause=不被暂停和使用或杀死的进程：
BlacklistFindWindowBox=指定窗口
>>>
```

If we go with "blacklist" (黑名单) we could at least be consistent -- `BlacklistPause=不被暂停和使用或杀死的进程：` and `BlacklistScrolllist=应该忽略滚动操作的窗口：` shall be some blacklists.

I circled around the wording back then.

**Comment by CJYKK** [comment]
My bad, I've been a bit too busy lately, I'll revise it asap.

**Comment by CJYKK** [comment]
I opened a new pull request, please check;)

**Pull request merged**
