### PR TITLE
Show all alt tab windows on Shift

### PR DESCRIPTION
**Pull request by mbartlett21**
This will show all the windows over all screens, and when one is selected that isn't on the current screen it will be brought to the current screen.

Also, without shift being held down, it will now show windows that are off-screen, but closest to the current monitor. This will probably cause the problems with VirtualWin from https://github.com/RamonUnch/AltSnap/issues/298#issuecomment-1263144263 to reappear.
I'm not sure of a way to prevent it from showing VirtualWin's windows without stopping it showing any windows that are off-screen, other than having it configurable as an option in the settings.

### CODE REVIEW

**Comment by RamonUnch** [comment]
Thanks a lot for your contribution, however, I think it would be better to just create a new action such as `AC_ALTTBAFULLLIST`.
Also an extra parameter should be set to `TrackMenuOfWindows()` to indicate if we want or not to move the window to pointed monitor and you could create a new function named MoveToCurrentMoniterIfNeeded() or something, just for clarity.

**Comment by RamonUnch** [comment]
I agree that a global setting makes sense for the *Move to the current monitor* setting this can apply to all list of windows but it actually makes a difference only for this `AltTabFullList` action so for now it is not needed.

**Comment by mbartlett21** [comment]
This was just what I have been running with for the past couple of months (just rebased on top of a recent commit).

I was saying about a global setting for whether to show windows that are off-screen completely (which appears to be how VirtualWin works)

**Comment by mbartlett21** [comment]
I've just redone the AltTabFullList to be a separate action and added the flag options to TrackMenuOfWindows.

**Comment by RamonUnch** [comment]
Wow that is quite nice indeed.

**Comment by mbartlett21** [comment]
I've added an option for IgnoreOffscreenWindows and fixed the list to include minimized windows again.

To test it you can add this to your ini file: (I haven't added it there because Github doesn't like showing differences well at all)
```ini
[Advanced]
IgnoreOffscreenWindows=0
; If set to 1, both AltTabList and AltTabFullList will no longer show
; windows that are off-screen.
```

**Comment by RamonUnch** [comment]
Perfect, Just the last change I would prefer to have an opt-in option with a name that include the `Menu` keyword. `MenuShowOffscreenWin` that would have to be set to.

**Comment by mbartlett21** [comment]
Ok. I've just pushed another commit changing that.

Suggested option for the ini:
```ini
MenuShowOffscreenWin=0
; If set to 1, both AltTabList and AltTabFullList will include windows
; that are off-screen.
```

**Comment by RamonUnch** [comment]
Very nice work, thanks.

**Pull request merged**
