### PR TITLE
A Little Better

### PR DESCRIPTION
**Pull request by CJYKK**
Please give me advice!

### CODE REVIEW

**Comment by RamonUnch** [comment]
For me it looks nice, you just forgot the Long click option, last time you proposed:
`InputMouseLongClickMove=长按左键移动窗口 (&v)`
I would add (&v) as accelerator as it is the English one.

**Comment by RamonUnch** [comment]
Also `AdvancedBLMaximized=在最大化窗口上禁用AltSnap (&d)` was in your previous patch...

**Comment by CJYKK** [comment]
Cool, thank you!

**Comment by CJYKK** [comment]
Updated again (/≧▽≦)/

**Comment by RamonUnch** [comment]
I do not speak Chinese (obviously), so I trust you and it seems fine to me :)

**Pull request merged**
